config/routes.rb
Rails.application.routes.draw do
  resources :grats
  get 'status', to: 'grats#status', as: 'status'
  
  resources :stocks
  
  get 'quote', to: 'stocks#quote', as: 'quote'
  get 'grats_s', to: 'stocks#grats', as: 'grats_s'
  get 'lastupdate', to: 'stocks#lastupdate', as: 'lastupdate'
  
  
  root 'stocks#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/grat.rb
class Grat < ApplicationRecord
  
  def self.history
    redis = [ ]
    text = ''
    grats = Grat.all
    remaining = [ 10724, 16271, 40213, 7770, 8245, 1, 1, 1, 1 ]
    fvm_funding = [ 582976.00, 3457800.00, 2565990.00, 882642.43, 1962304.40, 1, 1, 1, 1 ] 
    gains = [ ]
    options = [ ]
    total_gain = 0
    data = { }
    grats.each do |stock|
      current = stock.grat_stats
      gains.push current
      
      data[stock.symbol] = stock.gains
#      puts data.inspect
      
      total_gain += current[5]
#      puts stock.symbol
#      options.push stock.collar_stats

    end   
    
    daily_gain = 0
    residual_total_gain = 0
    daily_total_change = 0
    history = [ ]

    grats.each_with_index do |g,i| 
    residual_value =  gains[i][1] * ( remaining[i] - (fvm_funding[i] * 0.509009462) /  gains[i][1] )
    residual_total_gain = residual_total_gain + residual_value
    residual_shares = ( remaining[i] - (fvm_funding[i] * 0.509009462) /  gains[i][1] )
		  
		  
    daily_gain = daily_gain + gains[i][11]		  
    daily_total_change = daily_total_change + residual_shares * gains[i][2]
    
    remaining_shares = "#{ActiveSupport::NumberHelper.number_to_delimited('%.0f' % remaining[i])}"
    remaining_value = "#{ActiveSupport::NumberHelper.number_to_delimited('%.0f' % (remaining[i] * gains[i][1]) )}"
    second_yr_shares = "#{ActiveSupport::NumberHelper.number_to_delimited('%.0f' % ( (fvm_funding[i] * 0.509009462) /  gains[i][1] ) )}"
    resid_shares = "#{ActiveSupport::NumberHelper.number_to_delimited('%.0f' % residual_shares)}"
    resid_value = "#{ActiveSupport::NumberHelper.number_to_delimited('%.0f' % residual_value)}"
    daily_change = "#{ActiveSupport::NumberHelper.number_to_delimited('%.0f' % (gains[i][2]  * residual_shares) )}"
    day_gain = "#{ActiveSupport::NumberHelper.number_to_delimited('%.0f' % daily_gain)}"
    
    redis_data = [ g.symbol, remaining_shares, remaining_value, second_yr_shares, 
      resid_shares, resid_value, daily_change, day_gain ]
      
      redis.push redis_data

#    text += g.symbol + "<br>"
#    text += "Remaining Shares = #{ActiveSupport::NumberHelper.number_to_delimited('%.0f' % remaining[i])}<br>"
#    text += "Remaining Value = #{ActiveSupport::NumberHelper.number_to_delimited('%.0f' % (remaining[i] * gains[i][1]) )}<br>"
#    text += "2nd yr Shares = #{ActiveSupport::NumberHelper.number_to_delimited('%.0f' % ( (fvm_funding[i] * 0.509009462) /  gains[i][1] ) )}<br>"
#    text += "Residual Shares = #{ActiveSupport::NumberHelper.number_to_delimited('%.0f' % residual_shares)}<br>"
#    text += "Residual Value = #{ActiveSupport::NumberHelper.number_to_delimited('%.0f' % residual_value)}<br>"
#    text += "Daily Change = #{ActiveSupport::NumberHelper.number_to_delimited('%.0f' % (gains[i][2]  * residual_shares) )}<br>"
#    text += "<br>"
    
    history.push [ g.symbol, remaining[i].to_s, (remaining[i] * gains[i][1]).to_s, ((fvm_funding[i] * 0.509009462) /  gains[i][1]).to_s,
             residual_shares.to_s, residual_value.to_s, (gains[i][2] * residual_shares).to_s ]
    
    
    end
    
    resid_total_gain = "#{ActiveSupport::NumberHelper.number_to_delimited('%.0f' % residual_total_gain)}"
    redis.push resid_total_gain
    day_total_change = "#{ActiveSupport::NumberHelper.number_to_delimited('%.0f' % daily_total_change)}"
    redis.push day_total_change
    redis.push Time.now.to_s
    
    text += "Residual Total Gain = $#{ActiveSupport::NumberHelper.number_to_delimited('%.0f' % residual_total_gain)}<br>"
    text += "Daily Total = $#{ActiveSupport::NumberHelper.number_to_delimited('%.0f' % daily_total_change)}<br>"
    text += "<br>"
    
    return [ text, history, residual_total_gain.to_s, daily_total_change.to_s, redis ]
    
  end

  def current_price
    symbol, price, change = Options.repo_price(self.symbol)
    price = price.to_d
    change = change.to_d
    return price, change
  end

  def grat_stats
    quantity = self.quantity
    price, change = self.current_price
    cost = self.quantity * self.cost
    value = self.quantity * price
    gain = value - cost
    gain_p = 100 * (gain / cost)
    gain_change = quantity * change.to_f
    min_gain = (quantity * self.put_strike) - cost
    min_gain_p = 100 * (min_gain / cost)
    max_gain = (quantity * self.call_strike) - cost      
    max_gain_p = 100 * (max_gain / cost)
    return [ symbol, price, change, cost, value, gain, gain_p, min_gain, min_gain_p, max_gain, max_gain_p, gain_change ]
  end
  
  def gains
    gains = { }
    gains[:quantity] = self.quantity
    gains[:price], gains[:change] = self.current_price
    gains[:cost] = self.quantity * self.cost
    gains[:value] = self.quantity * gains[:price]
    gains[:gain] = gains[:value] - gains[:cost]
    gains[:gain_p] = 100 * (gains[:gain] / gains[:cost])
    gains[:gain_change] = gains[:quantity] * gains[:change]
    gains[:min_gain] = (gains[:quantity] * self.put_strike) - gains[:cost]
    gains[:min_gain_p] = 100 * (gains[:min_gain] / gains[:cost])
    gains[:max_gain] = (gains[:quantity] * self.call_strike) - gains[:cost]      
    gains[:max_gain_p] = 100 * (gains[:max_gain] / gains[:cost])
    return gains
  end
  
  def collars
    collars = { }
    collars[:quantity] = self.quantity
    put = Options.option_price(self.symbol, self.put_strike, self.put_exp_date,  'Put Option')
    call = Options.option_price(self.symbol, self.call_strike, self.call_exp_date, 'Call Option')
    collars[:put_bid] = put['Bid'].to_d
    collars[:put_ask] = put['Ask'].to_d
    collars[:put_buy] = collars[:put_ask] * quantity
		collars[:put_sale] = collars[:put_bid] * quantity
    collars[:call_bid] = call['Bid'].to_d
    collars[:call_ask] = call['Ask'].to_d
    collars[:call_sale] = collars[:call_bid] * quantity
    collars[:call_buy] = collars[:call_ask] * quantity
    collars[:collar_cost] = collars[:call_sale] - collars[:put_buy]
    collars[:collar_value] = collars[:put_sale] - collars[:call_buy]
    collars[:collar_net] = collars[:collar_value] - collars[:collar_cost]  
    return collars
  end
  
  def collar_stats
    quantity = self.quantity
    put = Options.option_price(self.symbol, self.put_strike, self.put_exp_date,  'Put Option')
    call = Options.option_price(self.symbol, self.call_strike, self.call_exp_date, 'Call Option')
    put_buy = put['Ask'].to_d * quantity
		put_sale = put['Bid'].to_d * quantity
    call_sale = call['Bid'].to_d * quantity
    call_buy = call['Ask'].to_d * quantity
    collar_cost = call_sale - put_buy
    collar_value = put_sale - call_buy
    collar_net = collar_value - collar_cost
    return [ put['Bid'].to_d, put['Ask'].to_d, call['Bid'].to_d, call['Ask'].to_d, collar_cost, collar_value, collar_net ]
  end
  
end

app/controllers/grats_controller.rb
class GratsController < ApplicationController
  before_action :set_grat, only: [:show, :edit, :update, :destroy]

  def status
    @grats = Grat.all
    @remaining = [ 10724, 16271, 40213, 7770, 8245 ]
    @fvm_funding = [ 582976.00, 3457800.00, 2565990.00, 882642.43, 1962304.40 ] 
    @gains = [ ]
    @options = [ ]
    @total_gain = 0
    @total_loss = 0
    @data = { }
    @grats.each do |stock|
      current = stock.grat_stats
      @gains.push current
      
      @data[stock.symbol] = stock.gains
#      puts @data.inspect
      
      
      if current[5] > 0 # losses don't offset
        @total_gain += current[5]
      else
        @total_loss += current[5]
      end
#      puts stock.symbol
#      @options.push stock.collar_stats

    end    
    
    h = Grat.history
    puts h
       
  end
  
  # GET /grats
  # GET /grats.json
  def index
    @grats = Grat.all
  end

  # GET /grats/1
  # GET /grats/1.json
  def show
  end

  # GET /grats/new
  def new
    @grat = Grat.new
  end

  # GET /grats/1/edit
  def edit
  end

  # POST /grats
  # POST /grats.json
  def create
    @grat = Grat.new(grat_params)

    respond_to do |format|
      if @grat.save
        format.html { redirect_to @grat, notice: 'Grat was successfully created.' }
        format.json { render :show, status: :created, location: @grat }
      else
        format.html { render :new }
        format.json { render json: @grat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /grats/1
  # PATCH/PUT /grats/1.json
  def update
    respond_to do |format|
      if @grat.update(grat_params)
        format.html { redirect_to @grat, notice: 'Grat was successfully updated.' }
        format.json { render :show, status: :ok, location: @grat }
      else
        format.html { render :edit }
        format.json { render json: @grat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grats/1
  # DELETE /grats/1.json
  def destroy
    @grat.destroy
    respond_to do |format|
      format.html { redirect_to grats_url, notice: 'Grat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grat
      @grat = Grat.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def grat_params
      params.require(:grat).permit(:close_date, :symbol, :quantity, :cost, :current_price, :call_exp_date, :call_strike, :call_bid, :call_ask, :put_exp_date, :note, :put_strike, :put_bid, :put_ask)
    end
        
end

app/helpers/grats_helper.rb
module GratsHelper
end

app/views/grats/edit.html.erb
<h1>Editing Grat</h1>

<%= render 'form', grat: @grat %>

<%= link_to 'Show', @grat %> |
<%= link_to 'Back', grats_path %>

app/views/grats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Grats</h1>

<table>
  <thead>
    <tr>
      <th>Close date</th>
      <th>Symbol</th>
      <th>Quantity</th>
      <th>Cost</th>
      <th>Current price</th>
      <th>Call exp date</th>
      <th>Call strike</th>
      <th>Call bid</th>
      <th>Call ask</th>
      <th>Put exp date</th>
      <th>Put strike</th>
      <th>Put bid</th>
      <th>Put ask</th>
      <th>Note</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @grats.each do |grat| %>
      <tr>
        <td><%= grat.close_date %></td>
        <td><%= grat.symbol %></td>
        <td><%= grat.quantity %></td>
        <td><%= grat.cost %></td>
        <td><%= grat.current_price %></td>
        <td><%= grat.call_exp_date %></td>
        <td><%= grat.call_strike %></td>
        <td><%= grat.call_bid %></td>
        <td><%= grat.call_ask %></td>
        <td><%= grat.put_exp_date %></td>
        <td><%= grat.put_strike %></td>
        <td><%= grat.put_bid %></td>
        <td><%= grat.put_ask %></td>
        <td><%= grat.note %></td>
        <td><%= link_to 'Show', grat %></td>
        <td><%= link_to 'Edit', edit_grat_path(grat) %></td>
        <td><%= link_to 'Destroy', grat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Grat', new_grat_path %>

app/views/grats/new.html.erb
<h1>New Grat</h1>

<%= render 'form', grat: @grat %>

<%= link_to 'Back', grats_path %>

app/views/grats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Close date:</strong>
  <%= @grat.close_date %>
</p>

<p>
  <strong>Symbol:</strong>
  <%= @grat.symbol %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @grat.quantity %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @grat.cost %>
</p>

<p>
  <strong>Current price:</strong>
  <%= @grat.current_price %>
</p>

<p>
  <strong>Call exp date:</strong>
  <%= @grat.call_exp_date %>
</p>

<p>
  <strong>Call strike:</strong>
  <%= @grat.call_strike %>
</p>

<p>
  <strong>Call bid:</strong>
  <%= @grat.call_bid %>
</p>

<p>
  <strong>Call ask:</strong>
  <%= @grat.call_ask %>
</p>

<p>
  <strong>Put exp date:</strong>
  <%= @grat.put_exp_date %>
</p>

<p>
  <strong>Put strike:</strong>
  <%= @grat.put_strike %>
</p>

<p>
  <strong>Put bid:</strong>
  <%= @grat.put_bid %>
</p>

<p>
  <strong>Put ask:</strong>
  <%= @grat.put_ask %>
</p>

<p>
  <strong>Note:</strong>
  <%= @grat.note %>
</p>


<%= link_to 'Edit', edit_grat_path(@grat) %> |
<%= link_to 'Back', grats_path %>

app/views/grats/status.new.html.erb
<div class="container">

<br>
<p>As of <%= Time.now.in_time_zone.strftime("%m/%d/%Y at %I:%M%p") %></p>

<div class="table-responsive">
	<table class="table table-bordered table-striped table-sm">
	  <thead>
		<tr>
		  <td colspan='4' class="table-primary">Initial GRATs on April 5, 2020</td>
		  <td colspan='4' class="table-secondary">Gain before any annuity payments</td>
		</tr>  
	    <tr>
	      <th>Symbol</th>
	      <th style="text-align: right">Shares</th>
		  <th style="text-align: right">Price</th>
		  <th style="text-align: right">Value</th>
	      <th style="text-align: right">Current Price</th>
	      <th style="text-align: right">Current Value</th>
	      <th style="text-align: right">Total Gain</th>		  
	      <th style="text-align: right">Percent Gain</th>		  
		  
	    </tr>
	  </thead>

	  <tbody>
		  <% @init_total_value = 0 %>
		  <% @current_total_value = 0 %>
		  <% @total_gain = 0 %>
		  <% @grats.each_with_index do |g,i| %> 
	      <tr>
	        <td><%= link_to g.symbol, edit_grat_path(g) %></td>
	        <td style="text-align: right"><%= number_with_precision(g.quantity, :precision => 0, :delimiter => ',') %></td>
			<td style="text-align: right"><%= number_to_currency(g.cost) %></td>
			<td style="text-align: right"><%= number_to_currency(@gains[i][3], precision: 0) %></td>
			<td style="text-align: right"><%= number_to_currency(@gains[i][1], precision: 0) %> (<%= number_to_currency(@gains[i][2], precision: 2) %>)</td>
			<td style="text-align: right"><%= number_to_currency(@gains[i][4], precision: 0) %> </td>
			<td style="text-align: right"><%= number_to_currency(@gains[i][5], precision: 0) %></td>
			<td style="text-align: right"><%= number_to_percentage(@gains[i][6], precision: 1) %></td>
			
			
			<% @init_total_value += @gains[i][3] %>
			<% @current_total_value += @gains[i][4] %>
		  	<% @total_gain +=  @gains[i][5] %>
			
	      </tr>		
		  <% end %>
  	    <tr>
  	      <td colspan='4' style="text-align: right"><%= number_to_currency(@init_total_value, precision: 0) %></td>
  	      <td colspan='2' style="text-align: right"><%= number_to_currency(@current_total_value, precision: 0) %></td>
  	      <td style="text-align: right"><%= number_to_currency(@total_gain, precision: 0) %></td>
  	      <td></td>
		 </tr>
	  </tbody>
	</table>
</div>

<br><br>



<div class="table-responsive">
	<table class="table table-bordered table-striped table-sm">
	  <thead>
		<tr>
		  <td colspan='4' class="table-info">1st Annuity Payment ( %50.909..) made on 5/25/2021</td>
		  <td colspan='4' class="table-success">Pending 2nd Annuity Payment to be made on or before 04/05/2022</td>
		</tr>  
	    <tr>
	      <th style="text-align: right">Symbol</th>
	      <th style="text-align: right">1st Annuity Shares</th>
	      <th style="text-align: right">Remaining Shares</th>
		  <th style="text-align: right">Remaining Value</th>
	      <th style="text-align: right">2nd Annuity Shares</th>
	      <th style="text-align: right">Net Shares</th>
	      <th style="text-align: right">Net Value</th>
	      <th style="text-align: right">Daily Change</th>		  
	    </tr>
	  </thead>
<% @daily_gain = 0 %>
<% @residual_total_gain = 0 %>
<% @daily_total_change = 0 %>
	  <tbody>
		  <% @total_remaining_value = 0 %>
		  
		  <% @grats.each_with_index do |g,i| %> 
		  <% @residual_value =  @gains[i][1] * ( @remaining[i] - (@fvm_funding[i] * 0.509009462) /  @gains[i][1] ) %>
		  <% @residual_total_gain = @residual_total_gain + @residual_value %>
		  <% @residual_shares = ( @remaining[i] - (@fvm_funding[i] * 0.509009462) /  @gains[i][1] )%>
		  
		  
<% @daily_gain = @daily_gain + @gains[i][11] %>		  
<% @daily_total_change = @daily_total_change + @residual_shares * @gains[i][2] %>
		  <% @total_remaining_value +=  @remaining[i] * @gains[i][1] %>

	      <tr>
	        <td style="text-align: right"><%= g.symbol %></td>
	        <td style="text-align: right"><%= number_with_precision(g.quantity - @remaining[i], :precision => 0, :delimiter => ',') %></td>
			<td style="text-align: right"><%= number_with_precision(@remaining[i], :precision => 0, :delimiter => ',') %></td>
			<td style="text-align: right"><%= number_to_currency(@remaining[i] * @gains[i][1], precision: 0) %></td>
			<td style="text-align: right"><%= number_with_precision( 
													( (@fvm_funding[i] * 0.509009462) /  @gains[i][1] ),
													 :precision => 0, :delimiter => ',') %></td>
			<td style="text-align: right"><%= number_with_precision( @residual_shares, :precision => 0, :delimiter => ',') %></td>
			<td style="text-align: right"><%= number_to_currency( @residual_value, precision: 0 ) %></td>
			<td style="text-align: right"><%= number_to_currency(@gains[i][2]  * @residual_shares, precision: 0) %> (<%= number_to_currency(@gains[i][2]) %>)</td>
			
	      </tr>		
		  <% end %>
  	    <tr>
  	      <td colspan='4' style="text-align: right"><%= number_to_currency(@total_remaining_value, precision: 0)  %></td>
  	      <td colspan='3' style="text-align: right"><%= number_to_currency(@residual_total_gain, precision: 0)  %></td>
  	      <td style="text-align: right"><%= number_to_currency(@daily_total_change, precision: 0) %></td>
		 </tr>
	  </tbody>
	</table>
</div>


			

<% @name = Hash.new %>
<% @series = Hash.new %>
<% @data = [ ] %>
<% REDIS.keys.sort.each { |k| @series[k.split(' ').first] = JSON.parse(REDIS.get(k))[5].gsub(',','').to_i } %>
<% @name['name'] = 'Total' %>
<% @name['data'] = @series %>
<% @data.push @name %>


<%= line_chart @data, adapter: "google", library: {
			seriesType: "line",
			title: "Total Net Value", chartArea: { width: '85%', height: '80%'},
			legend: { position: 'top', alignment: 'end' }, 
			hAxis: {title: "2021", format: 'MMM dd', gridlines: {color: 'rgb(211,211,211)', count: 6 } }, 
			vAxis: {gridlines: { color: 'rgb(211,211,211)', count: 20 } } 
			}, id: "Total", thousands: ",", prefix: "$", min: 3000000, max: 7500000, height: "700px", points: true %>




<% @data = [ ] %>
<% (0..4).each do |s| %>
	<% @series = Hash.new %>
		<% @stock = Hash.new %>
		<% REDIS.keys.sort.each do |k| %>			
			<% @series['name'] = JSON.parse(REDIS.get(k))[s][0] %>
	        <% @stock[k.split(' ').first] = JSON.parse(REDIS.get(k))[s][5].gsub(',','')  %>
		<% end %>
		<% @series['data'] = @stock %>
		<% @data.push @series %>
<% end %>

<%= line_chart @data, adapter: "google", library: {
			seriesType: "line",
			title: "Individual GRATs", chartArea: { width: '85%', height: '80%'},
			legend: { position: 'top', alignment: 'end' }, 
			hAxis: {title: "2021", format: 'MMM dd', gridlines: {color: 'rgb(211,211,211)', count: 6 } }, 
			vAxis: {gridlines: { color: 'rgb(211,211,211)', count: 50, prefix: "$" } } 
			}, id: "Individual", thousands: ",", prefix: "$", min: -100000, max: 3500000, height: "700px", points: false %>
			
<br>Update 8/12/2022

</div>

app/views/grats/status_old.html.erb
<div class="container">

<br><br>
<%= Time.now.in_time_zone.strftime("%m/%d/%Y at %I:%M%p") %>

<div class="table-responsive">
	<table class="table table-bordered table-striped table-sm">
	  <thead>
	    <tr>
	      <th>Symbol</th>
	      <th style="text-align: right">Quantity</th>
		  <th style="text-align: right">Cost</th>
	      <th style="text-align: right">Price</th>
	      <th style="text-align: right">Change</th>
	      <th style="text-align: right">Put Strike</th>
	      <th style="text-align: right">Call Strike</th>
		  		  
	      <th style="text-align: right">Minimum</th>
	      <th style="text-align: right">Current Gain</th>
	      <th style="text-align: right">Maximum</th>
	    </tr>
	  </thead>

	  <tbody>
		  <% @grats.each_with_index do |g,i| %> 
	      <tr>
	        <td><%= g.symbol %></td>
	        <td style="text-align: right"><%= number_with_precision(g.quantity, :precision => 0, :delimiter => ',') %></td>
			<td style="text-align: right"><%= number_to_currency(g.cost) %></td>
			<td style="text-align: right"><%= number_to_currency(@gains[i][1]) %></td>
			<td style="text-align: right"><%= number_to_currency(@gains[i][2]) %></td>
			<td style="text-align: right"><%= number_to_currency(g.put_strike, precision: 0) %> <%= link_to 'Edit', edit_grat_path(g) %></td>
			<td style="text-align: right"><%= number_to_currency(g.call_strike, precision: 0) %></td>
			
			<td style="text-align: right"><%= number_to_currency(@gains[i][7], precision: 0) %> 
											<%= number_to_percentage(@gains[i][8], precision: 1) %></td>
			<td style="text-align: right"><%= number_to_currency(@gains[i][5], precision: 0) %> 
											<%= number_to_percentage(@gains[i][6], precision: 1) %></td>
			<td style="text-align: right"><%= number_to_currency(@gains[i][9], precision: 0) %> 
											<%= number_to_percentage(@gains[i][10], precision: 1) %></td>
	      </tr>		
		  <% end %>
  	    <tr>
  	      <td></td>
  	      <td></td>
  	      <td></td>
  	      <td></td>
  	      <td></td>
  	      <td></td>
  	      <td></td>
  	      <td></td>
  	      <td style="text-align: right"><%= number_to_currency(@total_gain) %></td>
  	      <td></td>
		 </tr>
	  </tbody>
	</table>
</div>

<br><br>

<div class="table-responsive">
	<table class="table table-bordered table-striped table-sm">
	  <thead>
	    <tr>
	      <th>Date</th>
	      <th style="text-align: right">Symbol</th>
	      <th style="text-align: right">Price</th>
	      <th style="text-align: right">Change</th>
	      <th style="text-align: right">Gain</th>		  
	      <th style="text-align: right">Change</th>
	      <th style="text-align: right">Collar Cost</th>
	      <th style="text-align: right">Collar Value</th>
	      <th style="text-align: right">Net Collar Effect</th>
	    </tr>
	  </thead>

	  <tbody>
		  <% @grats.each_with_index do |g,i| %> 
	      <tr>
	        <td><%= g.close_date.strftime("%m/%d/%Y") %></td>
	        <td style="text-align: right"><%= g.symbol %></td>
			<td style="text-align: right"><%= number_to_currency(@gains[i][1]) %></td>
			<td style="text-align: right"><%= number_to_currency(@gains[i][2]) %></td>
			<td style="text-align: right"><%= number_to_currency(@gains[i][5], precision: 0) %></td>
			<td style="text-align: right"><%= number_to_currency(@gains[i][11], precision: 0) %></td>
			<td style="text-align: right"><%= number_to_currency(@options[i][4], precision: 0) %></td>
			<td style="text-align: right"><%= number_to_currency(@options[i][5], precision: 0) %></td>
			<td style="text-align: right"><%= number_to_currency(@options[i][6], precision: 0) %></td>
	      </tr>		
		  <% end %>
  	    <tr>
  	      <td></td>
  	      <td></td>
  	      <td></td>
  	      <td></td>
  	      <td></td>
  	      <td></td>
  	      <td style="text-align: right"><%= number_to_currency(@total_gain) %></td>
		 </tr>
	  </tbody>
	</table>
</div>


<br><br>

<div class="table-responsive">
	<table class="table table-bordered table-striped table-sm">
	  <thead>
	    <tr>
	      <th>Date</th>
	      <th style="text-align: right">Symbol</th>
	      <th style="text-align: right">Price</th>
	      <th style="text-align: right">Change</th>
	      <th style="text-align: right">Gain</th>		  
	      <th style="text-align: right">Change</th>
	      <th style="text-align: right">Collar Cost</th>
	      <th style="text-align: right">Collar Value</th>
	      <th style="text-align: right">Net Collar</th>
	    </tr>
	  </thead>

	  <tbody>
		  <% @grats.each_with_index do |g,i| %> 
	      <tr>
	        <td><%= g.close_date.strftime("%m/%d/%Y") %></td>
	        <td style="text-align: right"><%= g.symbol %> <%= g.id %></td>
			<td style="text-align: right"><%= number_to_currency(g.gains[:price]) %></td>
			<td style="text-align: right"><%= number_to_currency(g.gains[:change]) %></td>
			<td style="text-align: right"><%= number_to_currency(g.gains[:gain], precision: 0) %></td>
			<td style="text-align: right"><%= number_to_currency(g.gains[:gain_change], precision: 0) %></td>
			<td style="text-align: right"><%= number_to_currency(g.collars[:collar_cost], precision: 0) %> <%= g.collars[:put_ask] %></td>
			<td style="text-align: right"><%= number_to_currency(g.collars[:collar_value], precision: 0) %> <%= g.collars[:put_ask] %></td>
			<td style="text-align: right"><%= number_to_currency(g.collars[:collar_net], precision: 0) %></td>
	      </tr>		
		  <% end %>
  	    <tr>
  	      <td></td>
  	      <td></td>
  	      <td></td>
  	      <td></td>
  	      <td></td>
  	      <td></td>
  	      <td style="text-align: right"><%= number_to_currency(@total_gain) %></td>
		 </tr>
	  </tbody>
	</table>
</div>



</div>